package nextinnnovationsoft.com.weightlossrecepies;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by PT on 3/3/2017.
 */

public class WeightLossRecipesDataSource {

    public static List<Recipe> getRecipeList(){

        List<Recipe> recipeList = new ArrayList<>();
        recipeList.add(new Recipe("Dinner Recipes",R.drawable.easy_pork_chops_with_swee));
        recipeList.add(new Recipe("Smoothies Recipes",R.drawable.strawberry_oat_milk_smoothie));
        recipeList.add(new Recipe("Top 30 Weight Loss Recipes",R.drawable.one_pot_black_pepper_chicken));

        return  recipeList;
    }
    public  static  List<Recipe> getRecipeCategoryOneList(){
        List<Recipe> recipeList = new ArrayList<>();
        recipeList.add(new Recipe("NE  POT  LEMON  HERB  CHICKEN  &  RICE","Nutrition: 422 calories, 9.8 g fat (4.3 g saturated fat), 161 mg sodium, 39 g carbs, 1.7 g fiber, 2.2 g sugar, 42.2 g protein (calculated with unsalted butter, 1 teaspoon added salt, low sodium chicken broth)\n" +
                "Seven ingredients, one large skillet and 30 minutes are all you’ll need to make this delicious protein-filled meal. To amp up the fiber count and boost your dinner’s satiety factor, add some chopped broccoli or brussels sprouts to the mix. And to reach your weight loss goal even faster, get the inside scoop from these 50 Best-Ever Weight-Loss Secrets From Skinny People!\n",R.drawable.one_poto_lemon_herb_chicken));
        recipeList.add(new Recipe("EASY PORK CHOPS WITH SWEET AND SOUR GLAZE","Nutrition: 362 calories, 25.2 g fat (11 g saturated fat), 199 mg sodium, 14 g carbs, 13 g sugar, 18.2 g protein (calculated with no added salt and optional 1/4 teaspoon red pepper flakes)\n" +
                "Chops may not be the leanest cut of pork on the market, but a 3.5 serving of the protein source provides a decent hit of choline, a nutrient that attacks the gene mechanism that triggers the storage of fat around the liver. And by making this Asian-inspired dish at home, instead of ordering something similar from your local take-out joint, you’re saving tons of sodium, calories and sugar—without sacrificing flavors you crave. Looking for even more dinner recipes that don’t sacrifice calories for taste? Check out these 20 Best-Ever Recipes for Zero Belly.\n",R.drawable.easy_pork_chops_with_swee));
        recipeList.add(new Recipe("CREAMY CHICKEN QUINOA BROCCOLI CASSEROLE","Nutrition: 363 calories, 11 g fat (3.4 g saturated fat), 467 mg sodium, 3.3 g fiber, 3 g sugar, 33.7 g protein\n" +
                "Just because you’re trying to lose weight, doesn’t mean you have to give up savory comfort food—and this cheesy, bacon topped dish proves just that! By using quinoa in lieu of traditional white rice, the talented blogger behind this dish boosts the protein content six-fold and adds an additional 11.5 grams of waist-whittling fiber to her casserole creation. And thanks to the addition of broccoli, this dish provides a fair amount of vitamin C, a nutrient that counteracts cortisol, a stress hormone that promotes belly fat.\n",R.drawable.canteloupe_banana_smoothie));
        recipeList.add(new Recipe("tMEXICAN TORTILLA CASSEROLE","Nutrition: 424 calories, 13 g fat (6.6 g saturated fat), 324 mg sodium, 57.4 g carbs, 12.1 g fiber, 5.9 g sugar, 22.4 g protein (calculated with black beans)\n" +
                "This recipe relies on canned beans and a combination of frozen and no-chop veggies which keeps prep time to a quick 10-minutes. And after 20-minutes in the oven, this fiber and protein-rich one-dish wonder is ready to make its dinner table debut.\n",R.drawable.mexican_tortilla_cassrole));
        recipeList.add(new Recipe("SIMPLE SESAME CHICKEN","Nutrition: 435 calories, 21.8 g fat (5 g saturated fat), 611 mg sodium, 9 g carbs, 1.1 g fiber, 2.5 g sugar, 52.8 g protein (calculated without rice and with 2 tablespoons sesame seeds)\n" +
                "It may arrive at your front door in just 30 minutes flat, but if Chinese takeout is part of your weekly dinner lineup, it’s likely making it very difficult to shed unwanted pounds. Don’t believe it? Consider this: An order of sesame chicken from P.F Chang’s will cost you 890 calories and an entire day’s worth of blood pressure-spiking sodium. The solution? This homemade version, on the other hand, has a fraction of the calories and salt and can get on your kitchen table just as quickly. And speaking of speed, if you want to peel away the pounds sooner rather than later.\n",R.drawable.simple_sesame_chicken));
        recipeList.add(new Recipe("HARISSA AND CITRUS BAKED SALMON","Nutrition: 307 calories, 14 g fat (1.4 g saturated fat), 817 mg sodium, 13.5 g carbs, 9 g sugar, 31.6 g protein (calculated with 32 oz salmon and green onions)\n" +
                "Move over, sriracha, a new saucy condiment is bringing the heat to dinnertime dishes. Harissa, a paste made with hot chili peppers, garlic and smoky spices, joins together with citrus fruits and onions to create this unique—yet easy to make—salmon dish. To round out your meal, follow Sweet Phi’s lead and serve your fish with a side of roasted broccoli. The green cruciferous veggie contains a potent phytonutrient called sulforaphane that increase testosterone and fights off fat storage.\n",R.drawable.harissa_and_citrus));
        recipeList.add(new Recipe("3-indgredient_salmon","Nutrition: 236 calories, 11.3 g fat (1.7 g saturated fat), 79 mg sodium, 0.6 g carbs, 0.5 g sugar, 33.1 g protein (calculated without added salt)\n" +
                "Want to lose weight without going hungry? Wild salmon is a must-have. Not only is it rich in omega-3s, healthy fats that stave off metabolism-slowing inflammation, but it’s also a great source of protein, a nutrient that increases post-meal calorie burn by as much as 35 percent! Thankfully, it doesn’t take a lot of work to transform a raw fillet into a filling, delicious meal, and this recipe by The Healthy Maven proves just that. We love that it goes from the oven to your dinner table in just 20-minutes flat.\n",R.drawable.one_skillet_lemon_chicken_and_red_potatoes));
        recipeList.add(new Recipe("ONE SKILLET LEMON CHICKEN AND RED POTATOES","Nutrition: 310 calories, 22.3 g fat (5.7 g saturated fat), 195 mg sodium, 10.2 g carbs, 1.4 g fiber, 1.6 g sugar, 18.1 g protein\n" +
                "Yes, you read that correctly, we’re telling you to eat potatoes for weight loss. The reason: An Australian study that measured the satiety index of 38 popular foods found that white spuds were not only more filling and satisfying than things like cookies and cake (no surprise there), they also ranked better than healthy picks like brown rice and oatmeal. As a result, research participants ate less on the days they consumed them. Add this healthy meal to your weekly rotation and it may just be easier for you to say no to dessert.\n",R.drawable.ingredient_easy_white));
        recipeList.add(new Recipe("INGREDIENT EASY WHITE CHICKEN CHILI","Nutrition: 460 calories, 6.5 g fat (1.2 g saturated fat), 948 mg sodium, 43 g carbs, 14.6 g fiber, 5.8 g sugar, 53.3 g protein (calculated with cooked shredded chicken)\n" +
                "A chili recipe that comes together in just 15 minutes? It may sound too good to be true, but it’s not! The secret behind the speed? Pre-cooked chicken—it cuts the cooking time in half. To keep the calorie and fat counts reasonable, steer clear of the sour cream and crumbled tortilla chips add-ons. Instead, top off your bowl with some avocado (a fruit that’s been shown to lower BMI and whittle waistlines) and fresh cilantro.\n",R.drawable.ingredient_easy_white));
        recipeList.add(new Recipe("12-MINUTE PEANUT NOODLES","Nutrition: 380 calories, 11.3 g fat (2.7 g saturated fat), 778 mg sodium, 51 g carbs, 9 g fiber, 6 g sugar, 19.6 g protein (calculated with low sodium soy sauce)\n" +
                "There’s nothing not to love about stir-frys. They don’t take any special skills or crazy ingredients and they’re really quick to throw together. This vegan recipe, packed with vitamin-rich veggies, gets the bulk of its flavor from its peanut sauce, which calls for just five easy-to-find ingredients.\n",R.drawable.minute_peanut_noodles));
        return recipeList;
    }
    public static List<Recipe> getRecipeCategoryTwoList(){
        List<Recipe> recipeList = new ArrayList<>();
        recipeList.add(new Recipe("Avocado Loves Banana Smoothie","Avocado and banana make one of the best breakfast smoothie recipes; because, with such a blend, you obtain avocado’s omega-3, banana’s potassium and Greek yogurt’s protein, along with other nutrients and antioxidants. The best part is how it’s creamy, sweet and quick to do, which, as you know, fits busy mornings.",R.drawable.avocado_loves_banana_smoothie));
        recipeList.add(new Recipe("Canteloupe Banana Smoothie","Who knew that a melon with so much fiber, antioxidants and anti-inflammatory phytonutrients can be sweet and refreshing too? We love cantaloupe in any way or form–and especially in a breakfast smoothie. Try a cantaloupe-infused concoction at Cantaloupe Banana Smoothie Drink.",R.drawable.canteloupe_banana_smoothie));
        recipeList.add(new Recipe("Peachy Pineapple Smoothie","The summery fruits in our peachy pineapple smoothie create a healthy breakfast that’s sweet, refreshing and full of vitamins.",R.drawable.peachy_pineapple_smoothie));
        recipeList.add(new Recipe("Banana Peanut Butter Smoothie with Espresso","Need a wake-me-up in the morning? Try this wonderful Banana Peanut Butter Smoothie with Espresso! It’s naturally sweetened with Medjool date and perked up by a jolt of caffeine. It effortlessly wakes you up, and keeps you alert for the busy day ahead.",R.drawable.banana_peanut_butter_smoothie_with_honey_and_coconut));
        recipeList.add(new Recipe("Strawberry Banana Smoothie","Strawberry Banana Smoothie is a classic, but our recommendation, at Clean Eating Strawberry Banana Smoothie, is made with natural, clean ingredients including nonfat Greek yogurt, honey and organic unsweetened almond milk. It offers the same refreshing flavor as any strawberry-banana smoothies, but has less calories and fat, and fits right into the Clean Eating Diet Plan.",R.drawable.strawberry_banana_smoothie));
        recipeList.add(new Recipe("Raspberry Kiwi Smoothie","Supple raspberries and citrus-y kiwi combine into a refreshing combo that’s sweet enough for dessert yet healthy enough for breakfast. Attempt the recipe at Clean Eating Raspberry Kiwi Smoothie. You won’t be disappointed.",R.drawable.raspberry_kiwi_smoothie));
        recipeList.add(new Recipe("Banana Peanut Butter Smoothie With Honey","A hint of coconut milk and a drizzle of honey granted this Banana Peanut Butter Smoothie a unique flavor. It’s creamy, tasty and protein-rich–a fantastic way to end today’s list of Healthy Breakfast Smoothies!",R.drawable.banana_peanut_butter_smoothie_with_honey));
        recipeList.add(new Recipe("Blueberry Avocado Smoothie","Who knew that combining blueberry and avocado creates such a mean and lean breakfast? Check out this Blueberry and Avocado Smoothie that’s sweet, healthy and easy to do.",R.drawable.bleberry_avocado_smoothie));
        recipeList.add(new Recipe("Chocolate Hazelnut Smoothie Bowl","If you like the cocoa nutty flavor of chocolate and hazelnut in Nutella, you’ll love this luscious yet healthy chocolate hazelnut smoothie at With Food and Love.",R.drawable.individual_egg_spinach_bowl));
        recipeList.add(new Recipe("Strawberry Oat Meal Smoothie","This recipe is quite unique, because its main ingredient, oat milk, is made from scratch, with oat groat and purified water, through an overnight process. The smoothie contains other natural ingredients, like cocoa nibs and pure vanilla bean. The result is tastes quite amazing. You can find the recipe at strawberry_oat_milk_smoothie.",R.drawable.strawberry_oat_milk_smoothie));

        return recipeList;
    }
    public static List<Recipe> getRecipeCategoryThreeList(){
        List<Recipe> recipeList = new ArrayList<>();
        recipeList.add(new Recipe("Avocado Breakfast Pizza","Pizza for breakfast? You bet! This savory dish delivers creamy, buttery textures and a boatload of nutrients to keep you satisfied throughout the morning.",R.drawable.avacado_breakfast_pizza));
        recipeList.add(new Recipe("French Toast Casserole","This lightened version of the beloved breakfast treat delivers all the crispy, gooey deliciousness you love about French toast – without breaking your calorie bank!",R.drawable.french_toast_casserole));
        recipeList.add(new Recipe("10 Minute Stovetop Granola","You’re just 10 minutes away from a quick and crunchy breakfast stuffed with nutrient-rich superfoods like oats, walnuts, and honey. Pour a little milk on top and enjoy as a clean-eating cereal.",R.drawable.ten_minute_stovetop_granola));
        recipeList.add(new Recipe("Egg and Toast Breakfast Cups","Rise and shine to these protein-packed, mouthwateringly-rich breakfast cups! Gooey egg pairs wonderfully with crispy toast in this winning morning meal.",R.drawable.egg_and_toast_breakfast_cups));
        recipeList.add(new Recipe("Individual Egg & Spinach Bowl","Savory meets satisfying in this egg bake recipe, spotlighting two of the world’s healthiest superfoods, egg and spinach.",R.drawable.individual_egg_spinach_bowl));
        recipeList.add(new Recipe("Three Seed Berry Parfait","This berrylicious yogurt parfait is a snap to whip up. It’s the perfect go-to when you’re experiencing an early morning sweet tooth!",R.drawable.three_sees_berry_parfait));
        recipeList.add(new Recipe("Fried Eggs with Mushrooms & Brussels Sprouts","Swap your conventional breakfast with this delicious and hearty skillet breakfast. Mornings never tasted so good! ",R.drawable.fried_eggs_with_mushrooms_brussels_sprouts));
        recipeList.add(new Recipe("Chicken Salad Sandwich","A creamy, delicious chicken salad made with healthy ingredients. Enjoy half a sandwich with a cup of Tomato Basil Soup.",R.drawable.chicken_salad_sandwich));
        recipeList.add(new Recipe("Tomato, Hummus, and Spinach Salad Sandwich ","Ever try hummus on a sandwich? You’re in for a delicious treat with this easy prep recipe and just three main ingredients. ",R.drawable.tomato_hummus_and_spinach_salad));
        recipeList.add(new Recipe("Grilled Turkey Veggie Burger"," Carrots & zucchini make this burger ultra juicy and seriously delicious. Enjoy with your favorite clean & lean trimmings for that traditional burger taste.",R.drawable.brilled_turkey_veggie_burger));
        recipeList.add(new Recipe("Avocado Egg  Salad Sandwich","Enjoy a new twist on traditional egg salad. This skinnified version is a great choice for lunch plus it’s super easy to whip up and pack for the next day. ",R.drawable.avocado_egg_salad_sandwich));
        recipeList.add(new Recipe("Quinoa Fruit Salad with Honey Lime Vinaigrette"," Put some pep in your step with this bright and springy salad dish! Satisfying quinoa adds yummy nuttiness that blends beautifully with the tangy fruit.",R.drawable.quinoa_fruit_salad_with_honey_lime_vinaigrette));
        recipeList.add(new Recipe("Clean Eating Chicken Salad","A superfood chicken salad which includes chicken breasts, romaine lettuce, Greek yogurt, red grapes, all loaded into a whole wheat pita half. Oh my! ",R.drawable.clean_eating_chicken_salad));
        recipeList.add(new Recipe("Best Ever Chicken Lettuce Wraps","This Asian inspired recipe will have you craving take-out less and homemade dishes more. Make either the Cauliflower Stir-Fry or the Quinoa & Vegetable Stir-Fry and you’ve got a declious clean-eating meal. ",R.drawable.best_ever_chicken_lettuec_wraps));
        recipeList.add(new Recipe("Skinny Lasagna Rolls"," Stuffed with delicious traditional Italian ingredients, these perfectly proportioned lasagna rolls make the ultimate skinnifed dish when you’re craving something creamy and decadent.",R.drawable.skinny_lasagna_rolls));
        recipeList.add(new Recipe("One-Pot Black Pepper Chicken","This mouthwatering chicken dish, is a no-hassle recipe worth digging into! Just under 200 calories makes it taste even better. ",R.drawable.one_pot_black_pepper_chicken));
        recipeList.add(new Recipe("Blackened Sockeye Salmon","Salmon reigns supreme on the list of healthy fish. It carries a boatload of health benefits like omega-3s and powerful vitamins. This lovely sockeye dish is a snap to prepare and makes the perfect mid-week meal.",R.drawable.blackened_sockeye_salmon));
        recipeList.add(new Recipe("Stuffed Philly Chicken Peppers"," Gooey cheese melted atop chicken breast makes these stuffed peppers uber satisfying. The taste of Philly will wow your senses!",R.drawable.stuffed_philly_chicken_peppers));
        recipeList.add(new Recipe("Slow Cooker Cheesy Spinach Lasagna Recipe","Tender noodles meet ooey gooey cheese and savory spices in this lasagna recipe. Whipping up the prized pasta dish is a cinch, thanks to the crock-pot. ",R.drawable.slow_cooker_chessy_spinach_lasagna_recipe));
        recipeList.add(new Recipe("Crock Pot Low-Fat Beef Stew"," Cozy up with a bowl of this healthy version of the American classic. Made with 100% clean ingredients and based on a low-sodium broth, the savory stew will satisfy your tummy and warm your soul.",R.drawable.crock_pot_low_fat_beef_stew));
        recipeList.add(new Recipe("Tex Mex Meaty Mac ‘n’ Cheese Casserole","Mexican meets macaroni, forming a killer combination in this gooey home-cooked casserole! By opting for light, nutritious ingredients and bold spices, this winning recipe makes the ultimate comfort food hybrid without the guilt!",R.drawable.tex_mex_meaty_mac_n_cheese));
        return recipeList;
    }
}
